### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by KevinGoodman** [wyysf-98/GenMM#1]
Thanks for sharing. Any update plan for code release would be musch appreciated.

**Comment by wyysf-98** [comment]
I apologize for the delay in releasing the code due to my recent graduation and internship, which has kept me busy. However, I have just finished dealing with these matters, so I will work on releasing the code ASAP. In the meantime, you can try our web demo or download a very messy portion of the code from our hugging face space. I apologize for the delay and will do my best to release the code this weekend or next week.

**Comment by bbagwang** [comment]
Hello, @wyysf-98 Any update on the code release?
I can't wait to try it!

**Comment by wyysf-98** [comment]
> Hello, @wyysf-98 Any update on the code release? I can't wait to try it!

Really sorry for the delay, I am working on the visa and other things :(
You can try it on the web demo and get a messy code from hugging face. I have already finished the main part of the clean code and working on the blender addon and README. I think will be very very soon.

**Comment by SlimeVRX** [comment]
Please notify here when you release the code.

Thanks to the author's work!

**Comment by Ozawakun97** [comment]
Looking forward to the release of code

**Comment by waterxin** [comment]
> 

is it the whole project showed in hugging face?  Or just the demo part?

**Comment by wyysf-98** [comment]
> > 
> 
> is it the whole project showed in hugging face? Or just the demo part?

The hugging face space only contains a messy **part** of our code. I will release all the code by tomorrow. THANKS for waiting and sorry for the delay again :(

**Comment by FusionLi** [comment]
Hi, @wyysf-98 thanks for open sourcing your interesting work! I am wondering is there any plan to release the remaining part of the work:
![image](https://github.com/wyysf-98/GenMM/assets/12415051/53220b04-77f2-486f-9e93-d2e3b9a88c96)
. I am specifically interested in the application part.

**Comment by wyysf-98** [comment]
> Hi, @wyysf-98 thanks for open sourcing your interesting work! I am wondering is there any plan to release the remaining part of the work: ![image](https://user-images.githubusercontent.com/12415051/273535557-53220b04-77f2-486f-9e93-d2e3b9a88c96.png) . I am specifically interested in the application part.

Hello, Thank you for your attention to our work. Actually, I am working on the next work nowadays, so, I may not have much time to tidy up the code in the near future (perhaps after CVPR, in November). However, the implementation of the entire application is quite simple, and we have provided detailed explanations in the paper. You can also try to implement it by yourself. If you encounter any difficulties, I will try my best to provide assistance.
