### ISSUE TITLE
About application of GenMM

### ISSUE THREAD

**Issue by henrycjh** [wyysf-98/GenMM#10]
Hi, thanks for your great work! You have mentioned in the paper that one of the applications of GenMM is _Key Frame-guided Generation_, could you please show more detail about how to fix the specific frames through the whole generation process ?

**Comment by wyysf-98** [comment]
Hi, the implementation of `Key Frame-guided Generation` is very simple. 
You can manually set the keyframes during optimization by forcing certain frames to be the input motion. 
For example, you can change the code in https://github.com/wyysf-98/GenMM/blob/main/GenMM.py#L152, to manually set the keyframes in synthesized motion.
We will provide the code in the future :)

**Comment by wyysf-98** [comment]
I think it depends on the motion data and the keyframes selected, as for some keyframes, it is difficult to find some proper transition time points to get coherent results. So we call it keyframe **guided** generation, not keyframe generation.   

A simple trick you can try is to set consistent keyframes, such as the 0-10 frames as guided, which should get more stable results. 

I will also release the relative code in the near future, and you can wait patiently :)
