### ISSUE TITLE
addon dosnt install

### ISSUE THREAD

**Issue by kotaxyz** [wyysf-98/GenMM#2]
hi there ,thanks a lot for this awesome work , I tried to install the addon with blender 3.2.0 version but it didn't work , I downloaded the repo as zip and when i try to install it it don't show anywhere in the addons ,i use windows 10 with blender 3.2.0 , all other prerequisites installed successfully

**Comment by wyysf-98** [comment]
Hi, can you find it after clicking the 'Testing' button, or you can share me with your screenshot :) 

https://drive.google.com/file/d/1Ue-WeAgqrwr-2VJ7hyuayuVqXbjvZi6G/view?usp=sharing
