### ISSUE TITLE
Errors when follow blender add-on step

### ISSUE THREAD

**Issue by yijunqian** [wyysf-98/GenMM#8]
Hello! I am trying to follow the blender installation, but I am stuck on step 3.

After I type:
`(base) C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\bin>cd C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\bin && pip3 install -r docker/requirements.txt && pip3 install torch-scatter==2.1.0 -f https://data.pyg.org/whl/torch-1.12.0+cpu.html
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'docker/requirements.txt'`

I am using a window 10.

**Comment by wyysf-98** [comment]
Hi, I think you should download this repo. and then cd into the folder to run Step 3. As 'docker/requirements.txt' is a relative path.
