### ISSUE TITLE
Unable to find the GenMM tag

### ISSUE THREAD

**Issue by shravan-d** [wyysf-98/GenMM#9]
I have setup the environment, installed and enabled the add-on within blender. 
![blender](https://github.com/wyysf-98/GenMM/assets/58078248/1f19be6c-5b12-4d2d-94ed-fb3a03975284)
I imported a .bvh file and clicked on the Armature. At this point I am unable to find the GenMM tag. I'm new to Blender and have looked at the intuitive places, but could not find it. A screenshot as to where I can find and use the tag would be very helpful.

**Comment by wyysf-98** [comment]
Hi, the GenMM tag shows in the main view of Blender. You can do as following:
